const teamData = [
  {
    id: 1,
    name: "Dr. Elif Arslan",
    role: "Chief Dentist & Aesthetic Specialist",
    shortBio:
      "15 years of expertise in smile design. One of the leading specialists in cosmetic dentistry.",
    fullBio:
      "Dr. Elif Arslan graduated with honors from Istanbul University Faculty of Dentistry and completed her specialization in aesthetic dentistry in Germany. With over 15 years of clinical experience, she has transformed thousands of smiles using cutting-edge digital smile design technology. She is passionate about combining art and science to create natural, confident smiles tailored to each patient's unique facial structure.",
    specialties: [
      "Aesthetic Smile Design",
      "Porcelain Veneers",
      "Teeth Whitening",
      "Gum Contouring",
      "Full Mouth Rehabilitation",
    ],
    education: [
      "DDS — Istanbul University Faculty of Dentistry, 2008",
      "MSc Aesthetic Dentistry — Goethe University Frankfurt, 2011",
      "Digital Smile Design Certification — DSD Academy, 2016",
    ],
    experience: "15+ years",
    languages: ["Turkish", "German", "English"],
    certifications: [
      "European Board of Aesthetic Dentistry (EBAD)",
      "Digital Smile Design (DSD) Certified Clinician",
      "Invisalign Certified Provider",
    ],
    availableDays: ["Monday", "Tuesday", "Wednesday", "Friday"],
    photo:
      "https://images.unsplash.com/photo-1749638479393-5f2b74e2a66c?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    photoColor: "teal",
    initials: "EA",
    rating: 4.9,
    reviewCount: 312,
    patientsServed: 2400,
    tag: "Aesthetic Dentistry",
    tagIcon: "ti-award",
    featured: true,
  },
  {
    id: 2,
    name: "Dr. Burak Şahin",
    role: "Implant & Oral Surgery Specialist",
    shortBio:
      "European-certified implant surgeon with over 2,000 successful implant operations.",
    fullBio:
      "Dr. Burak Şahin is one of the most experienced implant surgeons in the region, having performed over 2,000 successful implant procedures. After completing his dental degree at Hacettepe University, he pursued advanced surgical training across Europe, earning his European Board of Oral Implantology certification. He specializes in complex full-arch restorations and bone grafting procedures, offering patients long-lasting, natural-looking results.",
    specialties: [
      "Dental Implants",
      "Full-Arch Restorations (All-on-4 / All-on-6)",
      "Bone Grafting",
      "Sinus Lifting",
      "Wisdom Tooth Extraction",
      "Oral Surgery",
    ],
    education: [
      "DDS — Hacettepe University Faculty of Dentistry, 2006",
      "Fellowship in Oral Implantology — University of Vienna, 2010",
      "Advanced Surgical Training — Straumann Institute, Basel, 2013",
    ],
    experience: "18+ years",
    languages: ["Turkish", "German", "English"],
    certifications: [
      "European Board of Oral Implantology (EBOI)",
      "Straumann Certified Implant Surgeon",
      "ITI (International Team for Implantology) Fellow",
    ],
    availableDays: ["Monday", "Wednesday", "Thursday", "Saturday"],
    photo:
      "https://images.unsplash.com/photo-1777331903190-341a3dd0441b?q=80&w=1548&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    photoColor: "blue",
    initials: "BŞ",
    rating: 5.0,
    reviewCount: 284,
    patientsServed: 2100,
    tag: "EU Certified",
    tagIcon: "ti-certificate",
    featured: true,
  },
  {
    id: 3,
    name: "Dr. Selin Yıldız",
    role: "Pediatric Dentist",
    shortBio:
      "Specially trained to help young patients grow up fear-free. Making dental visits fun since 2014.",
    fullBio:
      "Dr. Selin Yıldız dedicated her career to ensuring that children develop a positive relationship with dental care from an early age. She completed her pediatric dentistry residency at Ege University and received additional training in child psychology to better understand and manage dental anxiety in young patients. Her colorful, playful clinic environment and gentle approach make her a favorite among both children and parents.",
    specialties: [
      "Pediatric Preventive Care",
      "Dental Sealants",
      "Fluoride Treatment",
      "Early Orthodontic Assessment",
      "Trauma & Emergency Pediatric Care",
      "Conscious Sedation for Children",
    ],
    education: [
      "DDS — Ege University Faculty of Dentistry, 2012",
      "Residency in Pediatric Dentistry — Ege University, 2014",
      "Child Dental Anxiety Management — EAPD Course, 2017",
    ],
    experience: "10+ years",
    languages: ["Turkish", "German", "English"],
    certifications: [
      "European Academy of Paediatric Dentistry (EAPD) Member",
      "Pediatric Sedation Certified",
      "Child Psychological First Aid Trained",
    ],
    availableDays: ["Tuesday", "Wednesday", "Thursday", "Friday"],
    photo:
      "https://images.unsplash.com/photo-1527613426441-4da17471b66d?q=80&w=1704&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    photoColor: "coral",
    initials: "SY",
    rating: 4.9,
    reviewCount: 198,
    patientsServed: 1600,
    tag: "Pedodontist",
    tagIcon: "ti-heart",
    featured: true,
  },
  {
    id: 4,
    name: "Dr. Mert Doğan",
    role: "Orthodontist & Clear Aligner Expert",
    shortBio:
      "Specialist in traditional braces and invisible aligner systems for teens and adults.",
    fullBio:
      "Dr. Mert Doğan has been straightening smiles for over a decade, combining traditional orthodontic expertise with the latest invisible aligner technology. He completed his orthodontic specialization at Ankara University and pursued advanced Invisalign training in the Netherlands. He is known for his meticulous treatment planning and ability to achieve precise results even in complex malocclusion cases. Dr. Doğan treats both teenagers and adults, tailoring every treatment plan to the patient's lifestyle and aesthetic goals.",
    specialties: [
      "Invisalign & Clear Aligners",
      "Traditional Metal Braces",
      "Ceramic Braces",
      "Lingual Braces",
      "Retainers & Post-Treatment Care",
      "Jaw Alignment (Orthognathic Referrals)",
    ],
    education: [
      "DDS — Ankara University Faculty of Dentistry, 2009",
      "MSc Orthodontics — Ankara University, 2012",
      "Invisalign Advanced Training — Align Technology, Amsterdam, 2015",
    ],
    experience: "12+ years",
    languages: ["Turkish", "German", "Dutch", "English"],
    certifications: [
      "Invisalign Diamond Provider",
      "European Orthodontic Society (EOS) Member",
      "3M Unitek Certified Orthodontist",
    ],
    availableDays: ["Monday", "Tuesday", "Thursday", "Saturday"],
    photo:
      "https://images.unsplash.com/photo-1606811842243-af7e16970c1f?q=80&w=1548&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    photoColor: "blue",
    initials: "MD",
    rating: 4.8,
    reviewCount: 176,
    patientsServed: 1300,
    tag: "Orthodontics",
    tagIcon: "ti-align-center",
    featured: false,
  },
  {
    id: 5,
    name: "Dr. Aylin Çelik",
    role: "Periodontist & Gum Health Specialist",
    shortBio:
      "Expert in gum disease treatment and gum aesthetic procedures for a healthy smile foundation.",
    fullBio:
      "Dr. Aylin Çelik specializes in the health and aesthetics of the gums and supporting structures of the teeth. After completing her periodontics residency at Marmara University, she trained in laser periodontal therapy in Switzerland and has since introduced advanced laser treatments to Lumina Dental. She is particularly skilled in gum contouring, crown lengthening, and treating advanced periodontitis cases. Dr. Çelik firmly believes that a healthy smile starts with healthy gums.",
    specialties: [
      "Periodontal Disease Treatment",
      "Laser Gum Therapy",
      "Gum Contouring & Aesthetic Gum Surgery",
      "Crown Lengthening",
      "Gingival Graft Surgery",
      "Implant Maintenance & Peri-implantitis Treatment",
    ],
    education: [
      "DDS — Marmara University Faculty of Dentistry, 2011",
      "Residency in Periodontology — Marmara University, 2014",
      "Laser Dentistry Certification — Swiss Dental Academy, Zurich, 2018",
    ],
    experience: "11+ years",
    languages: ["Turkish", "German", "French", "English"],
    certifications: [
      "European Federation of Periodontology (EFP) Member",
      "Biolase Laser Certified Clinician",
      "Academy of Osseointegration Member",
    ],
    availableDays: ["Monday", "Wednesday", "Friday"],
    photo:
      "https://images.unsplash.com/photo-1681939282781-341ac4f61996?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    photoColor: "teal",
    initials: "AÇ",
    rating: 4.9,
    reviewCount: 143,
    patientsServed: 980,
    tag: "Periodontology",
    tagIcon: "ti-leaf",
    featured: false,
  },
  {
    id: 6,
    name: "Dr. Kerem Yılmaz",
    role: "Endodontist & Root Canal Specialist",
    shortBio:
      "Painless root canal treatments using microscope-assisted techniques and rotary systems.",
    fullBio:
      "Dr. Kerem Yılmaz has made it his mission to change the way patients think about root canal treatment — making it a comfortable, virtually painless experience. He completed his endodontic specialization at Istanbul University and trained in microscope-assisted endodontics in the United States. Using state-of-the-art rotary instrumentation and digital 3D imaging (CBCT), he handles even the most complex root canal cases with precision and efficiency. Dr. Yılmaz also specializes in dental trauma management and internal tooth bleaching.",
    specialties: [
      "Root Canal Treatment (Single & Multi-Visit)",
      "Microscope-Assisted Endodontics",
      "Endodontic Retreatment",
      "Apicoectomy (Endodontic Surgery)",
      "Dental Trauma Management",
      "Internal Tooth Bleaching",
    ],
    education: [
      "DDS — Istanbul University Faculty of Dentistry, 2010",
      "MSc Endodontics — Istanbul University, 2013",
      "Microscopic Endodontics Training — University of Pennsylvania, Philadelphia, 2016",
    ],
    experience: "13+ years",
    languages: ["Turkish", "German", "English"],
    certifications: [
      "European Society of Endodontology (ESE) Member",
      "American Association of Endodontists (AAE) Associate Member",
      "CBCT Interpretation Certified — Dentsply Sirona",
    ],
    availableDays: ["Tuesday", "Thursday", "Friday", "Saturday"],
    photo:
      "https://images.unsplash.com/photo-1758205308172-fc864545dcf7?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    photoColor: "coral",
    initials: "KY",
    rating: 4.8,
    reviewCount: 159,
    patientsServed: 1150,
    tag: "Endodontology",
    tagIcon: "ti-microscope",
    featured: false,
  },
];

export default teamData;
